//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.ModelBinding;

namespace MVCTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen()
        {
            this.AlmacenProducto = new HashSet<AlmacenProducto>();
        }
    
        public int idAlmacen { get; set; }
        //Se pueden añadir/modificar/forzar las formas en que se ven los nombres de los campos, por ejemplo.
        [DisplayName("Nombre")]
        [Required]
        public string Nombre { get; set; }

        [DisplayName("Ciudad")]
        [Required]
        public string Ciudad { get; set; }

        [DisplayName("Nombre")]
        //Una expresión regular sólo se valida cuando tiene datos, no cuando está vacía
        [RegularExpression("^[0-9]{5}$",ErrorMessage="Codigo postal incorrecto")]
        [Required]
        public int CPostal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenProducto> AlmacenProducto { get; set; }
    }
}
